//
//     Copyright 2022 The Dragonfly Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: pkg/rpc/dfproxy/dfproxy.proto

package dfproxy

import (
	context "context"
	base "d7y.io/dragonfly/v2/pkg/rpc/base"
	dfdaemon "d7y.io/dragonfly/v2/pkg/rpc/dfdaemon"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqType int32

const (
	ReqType_HeartBeat   ReqType = 0
	ReqType_CheckHealth ReqType = 1
	ReqType_StatTask    ReqType = 2
	ReqType_ImportTask  ReqType = 3
	ReqType_ExportTask  ReqType = 4
	ReqType_DeleteTask  ReqType = 5
)

// Enum value maps for ReqType.
var (
	ReqType_name = map[int32]string{
		0: "HeartBeat",
		1: "CheckHealth",
		2: "StatTask",
		3: "ImportTask",
		4: "ExportTask",
		5: "DeleteTask",
	}
	ReqType_value = map[string]int32{
		"HeartBeat":   0,
		"CheckHealth": 1,
		"StatTask":    2,
		"ImportTask":  3,
		"ExportTask":  4,
		"DeleteTask":  5,
	}
)

func (x ReqType) Enum() *ReqType {
	p := new(ReqType)
	*p = x
	return p
}

func (x ReqType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_rpc_dfproxy_dfproxy_proto_enumTypes[0].Descriptor()
}

func (ReqType) Type() protoreflect.EnumType {
	return &file_pkg_rpc_dfproxy_dfproxy_proto_enumTypes[0]
}

func (x ReqType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqType.Descriptor instead.
func (ReqType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_rpc_dfproxy_dfproxy_proto_rawDescGZIP(), []int{0}
}

type DfDaemonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatTask   *dfdaemon.StatTaskRequest   `protobuf:"bytes,1,opt,name=stat_task,json=statTask,proto3" json:"stat_task,omitempty"`
	ImportTask *dfdaemon.ImportTaskRequest `protobuf:"bytes,2,opt,name=import_task,json=importTask,proto3" json:"import_task,omitempty"`
	ExportTask *dfdaemon.ExportTaskRequest `protobuf:"bytes,3,opt,name=export_task,json=exportTask,proto3" json:"export_task,omitempty"`
	DeleteTask *dfdaemon.DeleteTaskRequest `protobuf:"bytes,4,opt,name=delete_task,json=deleteTask,proto3" json:"delete_task,omitempty"`
}

func (x *DfDaemonReq) Reset() {
	*x = DfDaemonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DfDaemonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DfDaemonReq) ProtoMessage() {}

func (x *DfDaemonReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DfDaemonReq.ProtoReflect.Descriptor instead.
func (*DfDaemonReq) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_dfproxy_dfproxy_proto_rawDescGZIP(), []int{0}
}

func (x *DfDaemonReq) GetStatTask() *dfdaemon.StatTaskRequest {
	if x != nil {
		return x.StatTask
	}
	return nil
}

func (x *DfDaemonReq) GetImportTask() *dfdaemon.ImportTaskRequest {
	if x != nil {
		return x.ImportTask
	}
	return nil
}

func (x *DfDaemonReq) GetExportTask() *dfdaemon.ExportTaskRequest {
	if x != nil {
		return x.ExportTask
	}
	return nil
}

func (x *DfDaemonReq) GetDeleteTask() *dfdaemon.DeleteTaskRequest {
	if x != nil {
		return x.DeleteTask
	}
	return nil
}

type DaemonProxyClientPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   ReqType           `protobuf:"varint,1,opt,name=type,proto3,enum=dfproxy.ReqType" json:"type,omitempty"`
	SeqNum uint64            `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Error  *base.GrpcDfError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DaemonProxyClientPacket) Reset() {
	*x = DaemonProxyClientPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonProxyClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonProxyClientPacket) ProtoMessage() {}

func (x *DaemonProxyClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonProxyClientPacket.ProtoReflect.Descriptor instead.
func (*DaemonProxyClientPacket) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_dfproxy_dfproxy_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonProxyClientPacket) GetType() ReqType {
	if x != nil {
		return x.Type
	}
	return ReqType_HeartBeat
}

func (x *DaemonProxyClientPacket) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *DaemonProxyClientPacket) GetError() *base.GrpcDfError {
	if x != nil {
		return x.Error
	}
	return nil
}

type DaemonProxyServerPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ReqType      `protobuf:"varint,1,opt,name=type,proto3,enum=dfproxy.ReqType" json:"type,omitempty"`
	SeqNum    uint64       `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DaemonReq *DfDaemonReq `protobuf:"bytes,3,opt,name=daemon_req,json=daemonReq,proto3" json:"daemon_req,omitempty"`
}

func (x *DaemonProxyServerPacket) Reset() {
	*x = DaemonProxyServerPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonProxyServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonProxyServerPacket) ProtoMessage() {}

func (x *DaemonProxyServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonProxyServerPacket.ProtoReflect.Descriptor instead.
func (*DaemonProxyServerPacket) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_dfproxy_dfproxy_proto_rawDescGZIP(), []int{2}
}

func (x *DaemonProxyServerPacket) GetType() ReqType {
	if x != nil {
		return x.Type
	}
	return ReqType_HeartBeat
}

func (x *DaemonProxyServerPacket) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *DaemonProxyServerPacket) GetDaemonReq() *DfDaemonReq {
	if x != nil {
		return x.DaemonReq
	}
	return nil
}

var File_pkg_rpc_dfproxy_dfproxy_proto protoreflect.FileDescriptor

var file_pkg_rpc_dfproxy_dfproxy_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x66, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x66, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x0b, 0x44, 0x66, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x36, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x66, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3c, 0x0a, 0x0b, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x64, 0x66, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3c, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x66, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3c, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x66,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12,
	0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x44, 0x66, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x17, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x52, 0x65, 0x71,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65,
	0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x71,
	0x4e, 0x75, 0x6d, 0x12, 0x33, 0x0a, 0x0a, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x44, 0x66, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x09, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2a, 0x67, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x10,
	0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x10,
	0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x10,
	0x05, 0x32, 0x61, 0x0a, 0x0b, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x52, 0x0a, 0x08, 0x44, 0x66, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x64,
	0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x20,
	0x2e, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x64, 0x37, 0x79, 0x2e, 0x69, 0x6f, 0x2f, 0x64,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x66, 0x6c, 0x79, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x64, 0x66, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_rpc_dfproxy_dfproxy_proto_rawDescOnce sync.Once
	file_pkg_rpc_dfproxy_dfproxy_proto_rawDescData = file_pkg_rpc_dfproxy_dfproxy_proto_rawDesc
)

func file_pkg_rpc_dfproxy_dfproxy_proto_rawDescGZIP() []byte {
	file_pkg_rpc_dfproxy_dfproxy_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_dfproxy_dfproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_dfproxy_dfproxy_proto_rawDescData)
	})
	return file_pkg_rpc_dfproxy_dfproxy_proto_rawDescData
}

var file_pkg_rpc_dfproxy_dfproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_rpc_dfproxy_dfproxy_proto_goTypes = []interface{}{
	(ReqType)(0),                       // 0: dfproxy.ReqType
	(*DfDaemonReq)(nil),                // 1: dfproxy.DfDaemonReq
	(*DaemonProxyClientPacket)(nil),    // 2: dfproxy.DaemonProxyClientPacket
	(*DaemonProxyServerPacket)(nil),    // 3: dfproxy.DaemonProxyServerPacket
	(*dfdaemon.StatTaskRequest)(nil),   // 4: dfdaemon.StatTaskRequest
	(*dfdaemon.ImportTaskRequest)(nil), // 5: dfdaemon.ImportTaskRequest
	(*dfdaemon.ExportTaskRequest)(nil), // 6: dfdaemon.ExportTaskRequest
	(*dfdaemon.DeleteTaskRequest)(nil), // 7: dfdaemon.DeleteTaskRequest
	(*base.GrpcDfError)(nil),           // 8: base.GrpcDfError
}
var file_pkg_rpc_dfproxy_dfproxy_proto_depIdxs = []int32{
	4, // 0: dfproxy.DfDaemonReq.stat_task:type_name -> dfdaemon.StatTaskRequest
	5, // 1: dfproxy.DfDaemonReq.import_task:type_name -> dfdaemon.ImportTaskRequest
	6, // 2: dfproxy.DfDaemonReq.export_task:type_name -> dfdaemon.ExportTaskRequest
	7, // 3: dfproxy.DfDaemonReq.delete_task:type_name -> dfdaemon.DeleteTaskRequest
	0, // 4: dfproxy.DaemonProxyClientPacket.type:type_name -> dfproxy.ReqType
	8, // 5: dfproxy.DaemonProxyClientPacket.error:type_name -> base.GrpcDfError
	0, // 6: dfproxy.DaemonProxyServerPacket.type:type_name -> dfproxy.ReqType
	1, // 7: dfproxy.DaemonProxyServerPacket.daemon_req:type_name -> dfproxy.DfDaemonReq
	2, // 8: dfproxy.DaemonProxy.Dfdaemon:input_type -> dfproxy.DaemonProxyClientPacket
	3, // 9: dfproxy.DaemonProxy.Dfdaemon:output_type -> dfproxy.DaemonProxyServerPacket
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_rpc_dfproxy_dfproxy_proto_init() }
func file_pkg_rpc_dfproxy_dfproxy_proto_init() {
	if File_pkg_rpc_dfproxy_dfproxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DfDaemonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonProxyClientPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonProxyServerPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_dfproxy_dfproxy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_dfproxy_dfproxy_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_dfproxy_dfproxy_proto_depIdxs,
		EnumInfos:         file_pkg_rpc_dfproxy_dfproxy_proto_enumTypes,
		MessageInfos:      file_pkg_rpc_dfproxy_dfproxy_proto_msgTypes,
	}.Build()
	File_pkg_rpc_dfproxy_dfproxy_proto = out.File
	file_pkg_rpc_dfproxy_dfproxy_proto_rawDesc = nil
	file_pkg_rpc_dfproxy_dfproxy_proto_goTypes = nil
	file_pkg_rpc_dfproxy_dfproxy_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaemonProxyClient is the client API for DaemonProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonProxyClient interface {
	// Dfdaemon proxy service. Note that proxy client acts as a daemon server,
	// and proxy server acts as a daemon client, so proxy client connects proxy
	// server and proxy server will send daemon request to proxy client via
	// DaemonProxyServerPacket, proxy client will send daemon response via
	// DaemonProxyClientPacket.
	Dfdaemon(ctx context.Context, opts ...grpc.CallOption) (DaemonProxy_DfdaemonClient, error)
}

type daemonProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonProxyClient(cc grpc.ClientConnInterface) DaemonProxyClient {
	return &daemonProxyClient{cc}
}

func (c *daemonProxyClient) Dfdaemon(ctx context.Context, opts ...grpc.CallOption) (DaemonProxy_DfdaemonClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DaemonProxy_serviceDesc.Streams[0], "/dfproxy.DaemonProxy/Dfdaemon", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonProxyDfdaemonClient{stream}
	return x, nil
}

type DaemonProxy_DfdaemonClient interface {
	Send(*DaemonProxyClientPacket) error
	Recv() (*DaemonProxyServerPacket, error)
	grpc.ClientStream
}

type daemonProxyDfdaemonClient struct {
	grpc.ClientStream
}

func (x *daemonProxyDfdaemonClient) Send(m *DaemonProxyClientPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *daemonProxyDfdaemonClient) Recv() (*DaemonProxyServerPacket, error) {
	m := new(DaemonProxyServerPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DaemonProxyServer is the server API for DaemonProxy service.
type DaemonProxyServer interface {
	// Dfdaemon proxy service. Note that proxy client acts as a daemon server,
	// and proxy server acts as a daemon client, so proxy client connects proxy
	// server and proxy server will send daemon request to proxy client via
	// DaemonProxyServerPacket, proxy client will send daemon response via
	// DaemonProxyClientPacket.
	Dfdaemon(DaemonProxy_DfdaemonServer) error
}

// UnimplementedDaemonProxyServer can be embedded to have forward compatible implementations.
type UnimplementedDaemonProxyServer struct {
}

func (*UnimplementedDaemonProxyServer) Dfdaemon(DaemonProxy_DfdaemonServer) error {
	return status.Errorf(codes.Unimplemented, "method Dfdaemon not implemented")
}

func RegisterDaemonProxyServer(s *grpc.Server, srv DaemonProxyServer) {
	s.RegisterService(&_DaemonProxy_serviceDesc, srv)
}

func _DaemonProxy_Dfdaemon_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonProxyServer).Dfdaemon(&daemonProxyDfdaemonServer{stream})
}

type DaemonProxy_DfdaemonServer interface {
	Send(*DaemonProxyServerPacket) error
	Recv() (*DaemonProxyClientPacket, error)
	grpc.ServerStream
}

type daemonProxyDfdaemonServer struct {
	grpc.ServerStream
}

func (x *daemonProxyDfdaemonServer) Send(m *DaemonProxyServerPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *daemonProxyDfdaemonServer) Recv() (*DaemonProxyClientPacket, error) {
	m := new(DaemonProxyClientPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DaemonProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfproxy.DaemonProxy",
	HandlerType: (*DaemonProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dfdaemon",
			Handler:       _DaemonProxy_Dfdaemon_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/rpc/dfproxy/dfproxy.proto",
}
